theme: jekyll-theme-cayman
github:
  repository_url: https://github.com/TzipHoro

title: Rebecca Horowitz
subtitle: (917)-933-1339 | Rebecca.Horowitz@outlook.com | www.linkedin.com/in/rebecca-horowitz-70878b154
link: "https://github.com/TzipHoro"
